#!/bin/sh

app=$HOME/app
dev=$HOME/dev

deps="obj9 mk 9yacc 9rc pp"
oldpwd=`pwd`

# Dependencies
cd $dev
for i in $deps ; do
	git clone $GIT/$i 
	stat=$?
	cd $i
	if test $stat != 0 ; then
		git pull
	fi
	test -x install && ./install
	cd ..
done

cd $oldpwd

./update

