#!/bin/sh

app=$HOME/app
dev=$HOME/dev
oldpwd=`pwd`

# Dependencies
cd $dev
git clone $GIT/obj9 $dev/obj9
git clone $GIT/mk $dev/mk
git clone $GIT/9yacc $dev/9yacc
git clone $GIT/9rc $dev/9rc
cd $dev/obj9 && ./install
cd $dev/mk && ./install
cd $dev/9yacc && ./install
cd $dev/9rc && ./install
cd $oldpwd

mkdir -p $APP//pkg
cp -f installers.tsv pkgs.tsv $APP/pkg

cp -f exe/pkg exe/pkgname $HOME/exe/
chmod 0755 $HOME/exe/pkg $HOME/exe/pkgname


